/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_ffmpeg_vv_MainActivity */

#ifndef _Included_com_android_ffmpeg_vv_MainActivity
#define _Included_com_android_ffmpeg_vv_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_ffmpeg_vv_MainActivity
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_ffmpeg_vv_MainActivity_avcodecinfo
  (JNIEnv *, jobject);

/*
 * Class:     com_android_ffmpeg_vv_MainActivity 这是流处理方式。
 * Method:    stream
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_ffmpeg_vv_MainActivity_stream
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
